// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath 'me.tatarka:gradle-retrolambda:3.2.5'
        classpath 'com.google.gms:google-services:4.2.0'
        classpath 'io.codearte.gradle.nexus:gradle-nexus-staging-plugin:0.5.3'
        classpath 'io.fabric.tools:gradle:1.30.0'
        classpath "com.newrelic.agent.android:agent-gradle-plugin:5.24.0"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

plugins {
    id 'com.gradle.build-scan' version '2.4.2'
}

buildScan {
//    licenseAgreementUrl = 'https://gradle.com/terms-of-service'
//    licenseAgree = 'yes'
    termsOfServiceUrl = 'https://gradle.com/terms-of-service'
    termsOfServiceAgree = 'yes'
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
        maven { url 'https://maven.google.com' }
        maven { url 'https://maven.fabric.io/public' }
        maven { url 'https://dl.bintray.com/guardian/android' }
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

// Define versions in a single place
ext {
    // Sdk and tools
    minSdkVersion = 21
    targetSdkVersion = 28
    compileSdkVersion = 28
    buildToolsVersion = '28.0.3'

    // App dependencies
    supportLibrary = '28.0.0'
    gsonVersion = '2.8.1'
    calligraphyVersion = '2.2.0'

    // Network
    rx2FastAndroidNetworking = '1.0.0'
    cookieJarVersion = 'v1.0.1'

    dagger2Version = '2.11'
    rxjava2Version = '2.0.6'
    rxandroidVersion = '2.0.1'
    butterKnifeVersion = '8.8.1'
    greenDaoVersion = '3.2.2'
    placeholderviewVersion = '0.6.1'
    debugDBVersion = '1.0.0'
    timberVersion = '4.5.1'
    guavaVersion = '22.0-android'
    numberPickerVersion = '2.4.4'

    //Test dependencies
    junitVersion = '4.12'
    espressoVersion = '2.2.2'
    mockitoVersion = '2.7.1'

    //Routing
    leakCanaryVersion = '1.6.3'
    conductorVersion = '3.0.0-rc2'
    paginateVersion = '0.5.1'

    //Image Loading
    glideVersion = '4.3.1'
    photoViewVersion = '2.0.0'

    flowLayoutVersion = '1.0.3'
    recyclerViewPagerVersion = 'v1.1.1'

    braintreeVersion = '2.12.0'
    facebookVersion = '4.28.0'

    gcmVersion = '16.1.0'
    crystalRangeSeekbarVersion = '1.1.1'
    stickyHeadersVersion = '0.4.3@aar'

    //transactiontoolarge logger
    tooLargeToolVersion = '0.1.3'
}
