apply plugin: 'com.android.application'
apply plugin: 'io.fabric'
apply plugin: 'newrelic'

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion

    lintOptions {
        disable 'MissingTranslation'
    }

    defaultConfig {
        applicationId "au.com.dealsdirect.rc"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        multiDexEnabled true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
    }

    signingConfigs {
        releaseConfig {
            storeFile file('ozsale.keystore')
            storePassword('ozsale')
            keyAlias "ozsale"
            keyPassword "ozsale"
        }
    }

    buildTypes {

        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.releaseConfig
            zipAlignEnabled true
        }
    }

    flavorDimensions "default"

    productFlavors {
        buyinviteRC {
            versionCode 1
            versionName "0.9"
            applicationId "au.com.buyinvite.rc"
            buildConfigField "String", "API_ROOT", "\"https://www.dealsdirect.com.au/\""
            buildConfigField "String", "API_LEGACY", "\"https://www.dealsdirect.com.au/papi/public/v3.20/\""
            buildConfigField "String", "ACCOUNT_ID", "\"A56B0D62-AEF6-4653-848E-2ECDDB6E9B8C\""
            resValue "string", "app_name", "buyinvite"
            resValue "bool", "debug_mode", "false"
        }

        buyinviteTest {
            versionCode 1
            versionName "0.9"
            applicationId "au.com.buyinvite.test"
            buildConfigField "String", "API_ROOT", "\"https://genie-ui-dealsdirect-pre.mysaledev.com/\""
            buildConfigField "String", "API_LEGACY", "\"https://api.mysaledev.com/public/v3.20/\""
            buildConfigField "String", "ACCOUNT_ID", "\"A56B0D62-AEF6-4653-848E-2ECDDB6E9B8C\""
            resValue "string", "app_name", "buyinvite Test"
            resValue "bool", "debug_mode", "true"
        }

        dealsDirectRC {
            versionCode 69
            versionName "2.3.1"
            applicationId "au.com.dealsdirect"
            buildConfigField "String", "API_ROOT", "\"https://www.dealsdirect.com.au/\""
            buildConfigField "String", "API_LEGACY", "\"https://www.dealsdirect.com.au/papi/public/v3.20/\""
            buildConfigField "String", "ACCOUNT_ID", "\"A56B0D62-AEF6-4653-848E-2ECDDB6E9B8C\""
            resValue "string", "app_name", "DealsDirect"
            resValue "bool", "debug_mode", "false"
        }

        dealsDirectTest {
            versionCode 68
            versionName "2.3.1"
            applicationId "au.com.dealsdirect.test"
            buildConfigField "String", "API_ROOT", "\"https://genie-ui-dealsdirect-pre.mysaledev.com/\""
            buildConfigField "String", "API_LEGACY", "\"https://api.mysaledev.com/public/v3.20/\""
            buildConfigField "String", "ACCOUNT_ID", "\"A56B0D62-AEF6-4653-848E-2ECDDB6E9B8C\""
            resValue "string", "app_name", "DealsDirect Test"
            resValue "bool", "debug_mode", "false"
        }

        ooRC {
            versionCode 9
            versionName "0.9"
            applicationId "au.com.oo.rc"
            buildConfigField "String", "API_ROOT", "\"https://www.oo.com.au/\""
            buildConfigField "String", "API_LEGACY", "\"https://www.oo.com.au/papi/public/v3.20/\""
            buildConfigField "String", "ACCOUNT_ID", "\"25D201EB-9A1C-4045-90B6-E6A9F122C7CB\""
            resValue "string", "app_name", "OO RC"
            resValue "bool", "debug_mode", "false"
        }

        ooTest {
            versionCode 11
            versionName "0.9"
            applicationId "au.com.oo.test"
            buildConfigField "String", "API_ROOT", "\"https://genie-ui-oo-pre.mysaledev.com/\""
            buildConfigField "String", "API_LEGACY", "\"https://api.mysaledev.com/public/v3.20/\""
            buildConfigField "String", "ACCOUNT_ID", "\"25D201EB-9A1C-4045-90B6-E6A9F122C7CB\""
            resValue "string", "app_name", "OO Test"
            resValue "bool", "debug_mode", "true"
        }

        topbuyRC {
            versionCode 66
            versionName "2.2.0"
            applicationId "au.com.topbuy"
            buildConfigField "String", "API_ROOT", "\"https://www.dealsdirect.com.au/\""
            buildConfigField "String", "API_LEGACY", "\"https://www.dealsdirect.com.au/papi/public/v3.17/\""
            buildConfigField "String", "ACCOUNT_ID", "\"A56B0D62-AEF6-4653-848E-2ECDDB6E9B8C\""
            resValue "string", "app_name", "TopBuy"
            resValue "bool", "debug_mode", "false"
//            buildConfigField "String", "API_ROOT", "\"https://www.topbuy.com.au/\""
//            buildConfigField "String", "API_LEGACY", "\"https://www.topbuy.com.au/papi/public/v3.18/\""
//            buildConfigField "String", "ACCOUNT_ID", "\"909E0AC5-908A-4A73-8E5C-5312DEEBD24C\""
        }

        ourpayTest {
            versionCode 1
            versionName "0.9"
            applicationId "au.com.ourpay.test"
            buildConfigField "String", "API_ROOT", "\"https://genie-ui-dealsdirect-pre.mysaledev.com/\""
            buildConfigField "String", "API_LEGACY", "\"https://api.mysaledev.com/public/v3.17/\""
            buildConfigField "String", "ACCOUNT_ID", "\"A56B0D62-AEF6-4653-848E-2ECDDB6E9B8C\""
        }

        topbuyTest {
            versionCode 67
            versionName "2.2.0"
            applicationId "au.com.topbuy.test"
            buildConfigField "String", "API_ROOT", "\"https://www.dealsdirect.com.au/\""
            buildConfigField "String", "API_LEGACY", "\"https://www.dealsdirect.com.au/papi/public/v3.17/\""
            buildConfigField "String", "ACCOUNT_ID", "\"A56B0D62-AEF6-4653-848E-2ECDDB6E9B8C\""
            resValue "string", "app_name", "TopBuy Test"
            resValue "bool", "debug_mode", "true"
//            buildConfigField "String", "API_ROOT", "\"https://geniemobileappsclientapi.herokuapp.com/sandbox/\""
//            buildConfigField "String", "API_LEGACY", "\"https://geniemobileappsclientapi.herokuapp.com/sandbox/public/v3.18/api.asmx/\""
//            buildConfigField "String", "ACCOUNT_ID", "\"909E0AC5-908A-4A73-8E5C-5312DEEBD24C\""
        }
    }

    sourceSets {
        dealsDirectRC {
            java.srcDirs = ['src/commonControllers/java/', 'src/commonActivity/java/', 'src/main/java/']
        }

        dealsDirectTest {
            java.srcDirs = ['src/commonControllers/java/', 'src/commonActivity/java/', 'src/main/java/']
        }

        ooRC {
            res.srcDir 'src/ooTest/res/'
            java.srcDirs = ['src/commonControllers/java/', 'src/commonActivity/java/', 'src/main/java/']
        }

        ooTest {
            java.srcDirs = ['src/commonControllers/java/', 'src/commonActivity/java/', 'src/main/java/']
        }

        buyinviteRC {
            res.srcDir 'src/buyinviteTest/res/'
            java.srcDirs = ['src/commonControllers/java/', 'src/commonActivity/java/', 'src/main/java/']
        }

        buyinviteTest {
            java.srcDirs = ['src/commonControllers/java/', 'src/commonActivity/java/', 'src/main/java']
        }

        ourpayTest {
            java.srcDirs = ['src/ourpayTest/java/', 'src/commonControllers/java/', 'src/main/java/']
        }

        topbuyTest {
            java.srcDirs = ['src/topbuyTest/java/', 'src/main/java/']
        }

        topbuyRC {
            res.srcDir 'src/topbuyTest/res/'
            java.srcDirs = ['src/topbuyTest/java/', 'src/main/java/']
        }

        main {
            java.srcDirs = ['src/main/java', 'src/uncommonOurpay/java/']
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    configurations.all {
        resolutionStrategy.force 'com.google.code.findbugs:jsr305:1.3.9'
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])

    // android support libraries
    compile "com.android.support:appcompat-v7:$rootProject.supportLibrary"
    compile "com.android.support:recyclerview-v7:$rootProject.supportLibrary"
    compile "com.android.support:cardview-v7:$rootProject.supportLibrary"
    compile "com.android.support:design:$rootProject.supportLibrary"
    compile "com.android.support:support-vector-drawable:$rootProject.supportLibrary"
    compile "com.android.support:animated-vector-drawable:$rootProject.supportLibrary"

    // font
    compile "uk.co.chrisjenx:calligraphy:$rootProject.calligraphyVersion"

    // network
    compile "com.amitshekhar.android:rx2-android-networking:$rootProject.rx2FastAndroidNetworking"

    // parser
    compile "com.google.code.gson:gson:$rootProject.gsonVersion"

    // database
    compile "org.greenrobot:greendao:$rootProject.greenDaoVersion"

    //cookie jar
    compile "com.github.franmontiel:PersistentCookieJar:$rootProject.cookieJarVersion"

    // debug database
    debugCompile "com.amitshekhar.android:debug-db:$rootProject.debugDBVersion"

    // dependency injection
    compile "com.google.dagger:dagger:$rootProject.dagger2Version"
    annotationProcessor "com.google.dagger:dagger-compiler:$rootProject.dagger2Version"
    provided 'javax.annotation:jsr250-api:1.0'
    compile 'javax.inject:javax.inject:1'

    // reactive
    compile "io.reactivex.rxjava2:rxjava:$rootProject.rxjava2Version"
    compile "io.reactivex.rxjava2:rxandroid:$rootProject.rxandroidVersion"

    // code generator for view
    compile "com.jakewharton:butterknife:$rootProject.butterKnifeVersion"
    annotationProcessor "com.jakewharton:butterknife-compiler:$rootProject.butterKnifeVersion"

    // swipe view
    compile "com.mindorks:placeholderview:$rootProject.placeholderviewVersion"

    // logger
    compile "com.jakewharton.timber:timber:$rootProject.timberVersion"

    // conductor
    compile "com.bluelinelabs:conductor:$rootProject.conductorVersion"
    compile "com.bluelinelabs:conductor-support:$rootProject.conductorVersion"

    // paginate
    compile "com.github.markomilos:paginate:$rootProject.paginateVersion"

    // leak canary
    debugCompile "com.squareup.leakcanary:leakcanary-android:$rootProject.leakCanaryVersion"
    releaseCompile "com.squareup.leakcanary:leakcanary-android-no-op:$rootProject.leakCanaryVersion"

    // recycler view pager
    compile "com.github.lsjwzh.RecyclerViewPager:lib:$rootProject.recyclerViewPagerVersion"
    // flow layout
    compile "com.zhy:flowlayout-lib:$rootProject.flowLayoutVersion"
    // photo view
    compile "com.github.chrisbanes:PhotoView:$rootProject.photoViewVersion"
    // bottom navigation
    compile 'com.aurelhubert:ahbottomnavigation:2.0.6'
    // circle indicator
    compile 'me.relex:circleindicator:1.2.2@aar'

    // glide
    compile "com.github.bumptech.glide:glide:$rootProject.glideVersion"

    // guava
    compile "com.google.guava:guava:$rootProject.guavaVersion"

    // braintree
    compile "com.braintreepayments.api:braintree:$rootProject.braintreeVersion"
    compile "com.braintreepayments.api:data-collector:$rootProject.braintreeVersion"

    // facebook
    compile "com.facebook.android:facebook-android-sdk:$rootProject.facebookVersion"

    // GCM
    compile "com.google.android.gms:play-services-gcm:$rootProject.gcmVersion"

    // Crystal Range Seekbar
    compile "com.crystal:crystalrangeseekbar:$rootProject.crystalRangeSeekbarVersion"

    //viewpager indicator
    compile 'me.relex:circleindicator:1.2.2@aar'

    // dependencies for local unit tests
    testCompile "junit:junit:$rootProject.ext.junitVersion"
    testCompile "org.mockito:mockito-core:$rootProject.mockitoVersion"
    testAnnotationProcessor "com.google.dagger:dagger-compiler:$rootProject.dagger2Version"
    testCompile 'org.json:json:20160810'

    // UI Testing
    androidTestCompile "com.android.support.test.espresso:espresso-core:$rootProject.espressoVersion"
    androidTestCompile "com.android.support.test.espresso:espresso-intents:$rootProject.espressoVersion"
    androidTestCompile "org.mockito:mockito-core:$rootProject.mockitoVersion"
    androidTestAnnotationProcessor "com.google.dagger:dagger-compiler:$rootProject.dagger2Version"

    // CLS
    compile('com.crashlytics.sdk.android:crashlytics:2.6.8@aar') {
        transitive = true
    }

    // Answers
    compile('com.crashlytics.sdk.android:answers:1.3.13@aar') {
        transitive = true
    }

    // NR
    compile 'com.newrelic.agent.android:android-agent:5.12.3'

    compile project(path: ':genie-utility')
    compile project(path: ':genie-animation')
    compile project(path: ':genie-views')
    compile project(path: ':CardForm')
    compile project(path: ':ptr-lib')

}

configurations.all {
    resolutionStrategy.force "com.android.support:support-annotations:$supportLibrary"
}

apply plugin: 'com.google.gms.google-services'
