import groovy.xml.XmlParser

import javax.inject.Inject

plugins {
    id "com.android.application"
    id "newrelic"
    id "com.google.gms.google-services"
    id "com.google.firebase.crashlytics"
}

def buildType

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion

    lintOptions {
        disable 'MissingTranslation'
    }

    defaultConfig {
        applicationId "au.com.dealsdirect"
        namespace "au.com.dealsdirect"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        multiDexEnabled true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
    }

    signingConfigs {
        releaseConfig {
            storeFile file('ozsale.keystore')
            storePassword('ozsale')
            keyAlias "ozsale"
            keyPassword "ozsale"
        }
    }

    buildTypes {

        // Always use release variant for deployment to QA and app release
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.releaseConfig
            ext.debugMode = "false"

            resValue "bool", "debug_mode", ext.debugMode
            aaptOptions.cruncherEnabled = true
            ext.alwaysUpdateBulidId = true
        }

        // Always use debug variant during development
        debug {
            ext.debugMode = "true"
            resValue "bool", "debug_mode", ext.debugMode
            aaptOptions.cruncherEnabled = false
            ext.alwaysUpdateBulidId = false
        }
    }

    flavorDimensions "default"

    productFlavors {
        buyinviteRC {
            versionCode 534
            versionName "8.16.1"
            applicationId "au.com.buyinvite.bi"

            buildConfigField "String", "APP_NAME", "\"buyinvite\""
            buildConfigField "boolean", "IS_TEST", "false"

            ext.appName = "buyinvite"
            ext.facebookAppId = "391019637656000"
            ext.facebookAppSecret = "1dea9436118690813bcc315ecfc28705"
            ext.facebookClientToken = "d5f7ea8f1814ead7a465009de837b890"

            resValue "string", "app_name", ext.appName
            resValue "string", "facebook_app_id", ext.facebookAppId
            resValue "string", "facebook_app_secret", ext.facebookAppSecret
            resValue "string", "facebook_client_token", ext.facebookClientToken
            resValue "string", "fb_login_protocol_scheme", "fb" + ext.facebookAppId
            resValue "string", "fb_page_id", "153472458025053"
            resValue "string", "twitter_user_id", "twitter://user?user_id=36309423"
            resValue "string", "app_uri_hostname", "www.buyinvite.com.au"
            resValue "string", "app_uri_klarna", "www.buyinvite.com.au.klarna"

            ext.newRelicAppToken = "AAf4ce8e1466bf9d9b7c3dcfdf7c569defebda9edc"
            resValue "string", "new_relic_app_token", ext.newRelicAppToken
            resValue "string", "gift_card_id", ""

            ext.reCaptchaSiteKey = "6LdxiZ4UAAAAAGKk5Xzpbps1vHtDy0cfAEbr-88n"
            resValue "string", "recaptcha_site_key", ext.reCaptchaSiteKey
        }

        buyinviteTest {
            versionCode 534
            versionName "8.16.1"
            applicationId "au.com.buyinvite.bi.test"

            buildConfigField "String", "APP_NAME", "\"buyinvite\""
            buildConfigField "boolean", "IS_TEST", "true"

            resValue "string", "app_name", "buyinvite Test"
            def facebookAppId = "391019637656000"
            resValue "string", "facebook_app_id", facebookAppId
            resValue "string", "facebook_app_secret", "1dea9436118690813bcc315ecfc28705"
            resValue "string", "facebook_client_token", "d5f7ea8f1814ead7a465009de837b890"
            resValue "string", "fb_login_protocol_scheme", "fb" + facebookAppId
            resValue "string", "fb_page_id", "153472458025053"
            resValue "string", "twitter_user_id", "twitter://user?user_id=36309423"
            resValue "string", "app_uri_hostname", "www.buyinvite.com.au"
            resValue "string", "app_uri_klarna", "www.buyinvite.com.au.klarna"

            ext.newRelicAppToken = "AAf4ce8e1466bf9d9b7c3dcfdf7c569defebda9edc"
            resValue "string", "new_relic_app_token", ext.newRelicAppToken
            resValue "string", "gift_card_id", ""

            ext.reCaptchaSiteKey = "6Lfch54UAAAAANa6APm8vBBUttkU6mJxX0M1Kti5"
            resValue "string", "recaptcha_site_key", ext.reCaptchaSiteKey
        }

        dealsDirectRC {
            versionCode 534
            versionName "8.16.1"
            applicationId "au.com.dealsdirect"

            buildConfigField "String", "APP_NAME", "\"dealsdirect\""
            buildConfigField "boolean", "IS_TEST", "false"

            ext.appName = "DealsDirect"
            ext.facebookAppId = "1650094968544406"
            ext.facebookAppSecret = "94da0f48bd2ffea25981e52c56f9260a"
            ext.facebookClientToken = "d5f7ea8f1814ead7a465009de837b890"

            resValue "string", "app_name", ext.appName
            resValue "string", "facebook_app_id", ext.facebookAppId
            resValue "string", "facebook_app_secret", ext.facebookAppSecret
            resValue "string", "facebook_client_token", ext.facebookClientToken
            resValue "string", "fb_login_protocol_scheme", "fb" + ext.facebookAppId
            resValue "string", "fb_page_id", "257280167216"
            resValue "string", "twitter_user_id", "twitter://user?user_id=37405859"
            resValue "string", "app_uri_hostname", "www.dealsdirect.com.au"
            resValue "string", "app_uri_klarna", "www.dealsdirect.com.au.klarna"

            ext.newRelicAppToken = "AAa9d543732ff39dddc60c9cb9ad8c9cf22297904b"
            resValue "string", "new_relic_app_token", ext.newRelicAppToken
            resValue "string", "gift_card_id", ""

            ext.reCaptchaSiteKey = "6LdxiZ4UAAAAAGKk5Xzpbps1vHtDy0cfAEbr-88n"
            resValue "string", "recaptcha_site_key", ext.reCaptchaSiteKey
        }

        dealsDirectTest {
            versionCode 534
            versionName "8.16.1"
            applicationId "au.com.dealsdirect.test"

            buildConfigField "String", "APP_NAME", "\"dealsdirect\""
            buildConfigField "boolean", "IS_TEST", "true"

            resValue "string", "app_name", "DealsDirect Test"
            def facebookAppId = "1658400667713836"
            resValue "string", "facebook_app_id", facebookAppId
            resValue "string", "facebook_app_secret", "38e0530d1a0339d117b5474f0731f2af"
            resValue "string", "facebook_client_token", "d5f7ea8f1814ead7a465009de837b890"
            resValue "string", "fb_login_protocol_scheme", "fb" + facebookAppId
            resValue "string", "fb_page_id", "257280167216"
            resValue "string", "twitter_user_id", "twitter://user?user_id=37405859"
            resValue "string", "app_uri_hostname", "www.dealsdirect.com.au"
            resValue "string", "app_uri_klarna", "www.dealsdirect.com.au.klarna"

            ext.newRelicAppToken = "AAa9d543732ff39dddc60c9cb9ad8c9cf22297904b"
            resValue "string", "new_relic_app_token", ext.newRelicAppToken
            resValue "string", "gift_card_id", ""

            ext.reCaptchaSiteKey = "6Lfch54UAAAAANa6APm8vBBUttkU6mJxX0M1Kti5"
            resValue "string", "recaptcha_site_key", ext.reCaptchaSiteKey
        }

        ooRC {
            versionCode 534
            versionName "8.16.1"
            applicationId "au.com.oo"

            buildConfigField "String", "APP_NAME", "\"oo\""
            buildConfigField "boolean", "IS_TEST", "false"

            ext.appName = "OO"
            ext.facebookAppId = "1654976038100746"
            ext.facebookAppSecret = "f372b6a78ffbb38215f796d1a8838bb2"
            ext.facebookClientToken = "d5f7ea8f1814ead7a465009de837b890"

            resValue "string", "app_name", ext.appName
            resValue "string", "facebook_app_id", ext.facebookAppId
            resValue "string", "facebook_app_secret", ext.facebookAppSecret
            resValue "string", "facebook_client_token", ext.facebookClientToken
            resValue "string", "fb_login_protocol_scheme", "fb" + ext.facebookAppId
            resValue "string", "fb_page_id", "10357598833"
            resValue "string", "twitter_user_id", "twitter://user?user_id=14730691"
            resValue "string", "app_uri_hostname", "www.oo.com.au"
            resValue "string", "app_uri_klarna", "www.oo.com.au.klarna"

            ext.newRelicAppToken = "AAb0a85221e0d2eb8f185c2c2a34c566840b593941"
            resValue "string", "new_relic_app_token", ext.newRelicAppToken
            resValue "string", "gift_card_id", ""

            ext.reCaptchaSiteKey = "6LdxiZ4UAAAAAGKk5Xzpbps1vHtDy0cfAEbr-88n"
            resValue "string", "recaptcha_site_key", ext.reCaptchaSiteKey
        }

        ooTest {
            versionCode 534
            versionName "8.16.1"
            applicationId "au.com.oo.test"

            buildConfigField "String", "APP_NAME", "\"oo\""
            buildConfigField "boolean", "IS_TEST", "true"

            resValue "string", "app_name", "OO Test"
            def facebookAppId = "600738863393881"
            resValue "string", "facebook_app_id", facebookAppId
            resValue "string", "facebook_app_secret", "576ebf7aba3f1488605eb8d8886911f6"
            resValue "string", "facebook_client_token", "d5f7ea8f1814ead7a465009de837b890"
            resValue "string", "fb_login_protocol_scheme", "fb" + facebookAppId
            resValue "string", "fb_page_id", "10357598833"
            resValue "string", "twitter_user_id", "twitter://user?user_id=14730691"
            resValue "string", "app_uri_hostname", "www.oo.com.au"
            resValue "string", "app_uri_klarna", "www.oo.com.au.klarna"

            ext.newRelicAppToken = "AAb0a85221e0d2eb8f185c2c2a34c566840b593941"
            resValue "string", "new_relic_app_token", ext.newRelicAppToken
            resValue "string", "gift_card_id", ""

            ext.reCaptchaSiteKey = "6Lfch54UAAAAANa6APm8vBBUttkU6mJxX0M1Kti5"
            resValue "string", "recaptcha_site_key", ext.reCaptchaSiteKey
        }

        ozsaleRC {
            versionCode 534
            versionName "8.16.1"
            applicationId "au.com.ozsale"

            buildConfigField "String", "APP_NAME", "\"ozsale\""
            buildConfigField "boolean", "IS_TEST", "false"

            ext.appName = "OZSALE"
            ext.facebookAppId = "421544284547550"
            ext.facebookAppSecret = "f08401cb63ac18241e51e2184d8cd80a"
            ext.facebookClientToken = "cf2a2da0be692da07658cfc095e2b1ee"

            resValue "string", "app_name", ext.appName
            resValue "string", "facebook_app_id", ext.facebookAppId
            resValue "string", "facebook_app_secret", ext.facebookAppSecret
            resValue "string", "facebook_client_token", ext.facebookClientToken
            resValue "string", "fb_login_protocol_scheme", "fb" + ext.facebookAppId
            resValue "string", "fb_page_id", "160420993982663"
            resValue "string", "twitter_user_id", "twitter://user?user_id=25256714"
            resValue "string", "app_uri_hostname", "www.ozsale.com.au"
            resValue "string", "app_uri_klarna", "www.ozsale.com.au.klarna"

            ext.newRelicAppToken = "AA81128f803ab5bdb52bb2d4f6b19d29f0bb62bca1"
            resValue "string", "new_relic_app_token", ext.newRelicAppToken
            resValue "string", "gift_card_id", "hHjxmc1ZTEOCgJrLGobtlQ"

            ext.reCaptchaSiteKey = "6LdxiZ4UAAAAAGKk5Xzpbps1vHtDy0cfAEbr-88n"
            resValue "string", "recaptcha_site_key", ext.reCaptchaSiteKey
        }

        ozsaleTest {
            versionCode 534
            versionName "8.16.1"
            applicationId "au.com.ozsale.test"

            ext.appName = "OZSALE Test"
            ext.facebookAppId = "437865102935987"
            ext.facebookAppSecret = "5c6326d03e5d2ba866ecada5b206b6d6"
            ext.facebookClientToken = "cf2a2da0be692da07658cfc095e2b1ee"

            buildConfigField "String", "APP_NAME", "\"ozsale\""
            buildConfigField "boolean", "IS_TEST", "true"

            resValue "string", "app_name", ext.appName
            resValue "string", "facebook_app_id", ext.facebookAppId
            resValue "string", "facebook_app_secret", ext.facebookAppSecret
            resValue "string", "facebook_client_token", ext.facebookClientToken
            resValue "string", "fb_login_protocol_scheme", "fb" + ext.facebookAppId
            resValue "string", "fb_page_id", "160420993982663"
            resValue "string", "twitter_user_id", "twitter://user?user_id=25256714"
            resValue "string", "app_uri_hostname", "www.ozsale.com.au"
            resValue "string", "app_uri_klarna", "www.ozsale.com.au.klarna"

            ext.newRelicAppToken = "AA81128f803ab5bdb52bb2d4f6b19d29f0bb62bca1"
            resValue "string", "new_relic_app_token", ext.newRelicAppToken
            resValue "string", "gift_card_id", "hHjxmc1ZTEOCgJrLGobtlQ"

            ext.reCaptchaSiteKey = "6Lfch54UAAAAANa6APm8vBBUttkU6mJxX0M1Kti5"
            resValue "string", "recaptcha_site_key", ext.reCaptchaSiteKey
        }

        singsaleRC {
            versionCode 534
            versionName "8.16.1"
            applicationId "sg.com.singsale"

            buildConfigField "String", "APP_NAME", "\"singsale\""
            buildConfigField "boolean", "IS_TEST", "false"

            ext.appName = "SINGSALE"
            ext.facebookAppId = "213701285425668"
            ext.facebookAppSecret = "586750a24521ba339ff775ff2d729eb8"
            ext.facebookClientToken = "0eb39d9137e988f8afb399387598d356"

            resValue "string", "app_name", ext.appName
            resValue "string", "facebook_app_id", ext.facebookAppId
            resValue "string", "facebook_app_secret", ext.facebookAppSecret
            resValue "string", "facebook_client_token", ext.facebookClientToken
            resValue "string", "fb_login_protocol_scheme", "fb" + ext.facebookAppId
            resValue "string", "fb_page_id", "181383195228374"
            resValue "string", "twitter_user_id", "twitter://user?user_id=524844978"
            resValue "string", "app_uri_hostname", "www.singsale.com.sg"
            resValue "string", "app_uri_klarna", "www.singsale.com.sg.klarna"

            ext.newRelicAppToken = "AA7859bf063d467b13d1118979fb839dec128eb88a"
            resValue "string", "new_relic_app_token", ext.newRelicAppToken
            resValue "string", "gift_card_id", "VK14gfQWa02i5K12OaA5aA"

            ext.reCaptchaSiteKey = "6LdxiZ4UAAAAAGKk5Xzpbps1vHtDy0cfAEbr-88n"
            resValue "string", "recaptcha_site_key", ext.reCaptchaSiteKey
        }

        singsaleTest {
            versionCode 534
            versionName "8.16.1"
            applicationId "sg.com.singsale.test"

            buildConfigField "String", "APP_NAME", "\"singsale\""
            buildConfigField "boolean", "IS_TEST", "true"

            resValue "string", "app_name", "SINGSALE Test"
            def facebookAppId = "213701285425668"
            resValue "string", "facebook_app_id", facebookAppId
            resValue "string", "facebook_app_secret", "586750a24521ba339ff775ff2d729eb8"
            resValue "string", "facebook_client_token", "0eb39d9137e988f8afb399387598d356"
            resValue "string", "fb_login_protocol_scheme", "fb" + facebookAppId
            resValue "string", "fb_page_id", "181383195228374"
            resValue "string", "twitter_user_id", "twitter://user?user_id=524844978"
            resValue "string", "app_uri_hostname", "www.singsale.com.sg"
            resValue "string", "app_uri_klarna", "www.singsale.com.sg.klarna"

            ext.newRelicAppToken = "AA7859bf063d467b13d1118979fb839dec128eb88a"
            resValue "string", "new_relic_app_token", ext.newRelicAppToken
            resValue "string", "gift_card_id", "VK14gfQWa02i5K12OaA5aA"

            ext.reCaptchaSiteKey = "6Lfch54UAAAAANa6APm8vBBUttkU6mJxX0M1Kti5"
            resValue "string", "recaptcha_site_key", ext.reCaptchaSiteKey
        }

        nzsaleRC {
            versionCode 534
            versionName "8.16.1"
            applicationId "nz.co.nzsale"

            buildConfigField "String", "APP_NAME", "\"nzsale\""
            buildConfigField "boolean", "IS_TEST", "false"

            ext.appName = "NZSALE"
            ext.facebookAppId = "122094841270614"
            ext.facebookAppSecret = "c427c4000b760c98c818350619930764"
            ext.facebookClientToken = "3afb4e0406bc0e0bfcb5d87f79c8bafd"

            resValue "string", "app_name", ext.appName
            resValue "string", "facebook_app_id", ext.facebookAppId
            resValue "string", "facebook_app_secret", ext.facebookAppSecret
            resValue "string", "facebook_client_token", ext.facebookClientToken
            resValue "string", "fb_login_protocol_scheme", "fb" + ext.facebookAppId
            resValue "string", "fb_page_id", "293974924171"
            resValue "string", "twitter_user_id", "twitter://user?user_id=61630958"
            resValue "string", "app_uri_hostname", "www.nzsale.co.nz"
            resValue "string", "app_uri_klarna", "www.nzsale.co.nz.klarna"

            ext.newRelicAppToken = "AAfebece95884f3f5bc6acaacb76d02440c0f7eb85"
            resValue "string", "new_relic_app_token", ext.newRelicAppToken
            resValue "string", "gift_card_id", "w95zHeQSyUe2AjkNuGd_BQ"

            ext.reCaptchaSiteKey = "6LdxiZ4UAAAAAGKk5Xzpbps1vHtDy0cfAEbr-88n"
            resValue "string", "recaptcha_site_key", ext.reCaptchaSiteKey
        }

        nzsaleTest {
            versionCode 534
            versionName "8.16.1"
            applicationId "nz.co.nzsale.test"

            buildConfigField "String", "APP_NAME", "\"nzsale\""
            buildConfigField "boolean", "IS_TEST", "true"

            resValue "string", "app_name", "NZSALE Test"
            def facebookAppId = "122094841270614"
            resValue "string", "facebook_app_id", facebookAppId
            resValue "string", "facebook_app_secret", "c427c4000b760c98c818350619930764"
            resValue "string", "facebook_client_token", "3afb4e0406bc0e0bfcb5d87f79c8bafd"
            resValue "string", "fb_login_protocol_scheme", "fb" + facebookAppId
            resValue "string", "fb_page_id", "293974924171"
            resValue "string", "twitter_user_id", "twitter://user?user_id=61630958"
            resValue "string", "app_uri_hostname", "www.nzsale.co.nz"
            resValue "string", "app_uri_klarna", "www.nzsale.co.nz.klarna"

            ext.newRelicAppToken = "AAfebece95884f3f5bc6acaacb76d02440c0f7eb85"
            resValue "string", "new_relic_app_token", ext.newRelicAppToken
            resValue "string", "gift_card_id", "w95zHeQSyUe2AjkNuGd_BQ"

            ext.reCaptchaSiteKey = "6Lfch54UAAAAANa6APm8vBBUttkU6mJxX0M1Kti5"
            resValue "string", "recaptcha_site_key", ext.reCaptchaSiteKey
        }

        mysaleRC {
            versionCode 534
            versionName "8.16.1"
            applicationId "my.mysale.mysale"

            buildConfigField "String", "APP_NAME", "\"mysale\""
            buildConfigField "boolean", "IS_TEST", "false"

            ext.appName = "MYSALE"
            ext.facebookAppId = "485479254797079"
            ext.facebookAppSecret = "fee7b274d99b23eca0c283d48b2f453a"
            ext.facebookClientToken = "f31b297c05bb3c86769aec298e9ca36e"

            resValue "string", "app_name", ext.appName
            resValue "string", "facebook_app_id", ext.facebookAppId
            resValue "string", "facebook_app_secret", ext.facebookAppSecret
            resValue "string", "facebook_client_token", ext.facebookClientToken
            resValue "string", "fb_login_protocol_scheme", "fb" + ext.facebookAppId
            resValue "string", "fb_page_id", "161478120632146"
            resValue "string", "twitter_user_id", "twitter://user?user_id=524892602"
            resValue "string", "app_uri_hostname", "www.mysale.my"
            resValue "string", "app_uri_klarna", "www.mysale.my.klarna"

            ext.newRelicAppToken = "AAfb90a146f4b17ba00df83492608b2d7057e99e16"
            resValue "string", "new_relic_app_token", ext.newRelicAppToken
            resValue "string", "gift_card_id", ""

            ext.reCaptchaSiteKey = "6LdxiZ4UAAAAAGKk5Xzpbps1vHtDy0cfAEbr-88n"
            resValue "string", "recaptcha_site_key", ext.reCaptchaSiteKey
        }

        mysaleTest {
            versionCode 534
            versionName "8.16.1"
            applicationId "my.mysale.mysaleTest"

            buildConfigField "String", "APP_NAME", "\"mysale\""
            buildConfigField "boolean", "IS_TEST", "true"

            resValue "string", "app_name", "MYSALE Test"
            def facebookAppId = "485479254797079"
            resValue "string", "facebook_app_id", facebookAppId
            resValue "string", "facebook_app_secret", "fee7b274d99b23eca0c283d48b2f453a"
            resValue "string", "facebook_client_token", "f31b297c05bb3c86769aec298e9ca36e"
            resValue "string", "fb_login_protocol_scheme", "fb" + facebookAppId
            resValue "string", "fb_page_id", "161478120632146"
            resValue "string", "twitter_user_id", "twitter://user?user_id=524892602"
            resValue "string", "app_uri_hostname", "www.mysale.my"
            resValue "string", "app_uri_klarna", "www.mysale.my.klarna"

            ext.newRelicAppToken = "AAfb90a146f4b17ba00df83492608b2d7057e99e16"
            resValue "string", "new_relic_app_token", ext.newRelicAppToken
            resValue "string", "gift_card_id", ""

            ext.reCaptchaSiteKey = "6Lfch54UAAAAANa6APm8vBBUttkU6mJxX0M1Kti5"
            resValue "string", "recaptcha_site_key", ext.reCaptchaSiteKey
        }

    }

    sourceSets {
        dealsDirectRC {
            res.srcDirs = ['src/dealsDirectRC/res', 'src/commonRes/res']
            java.srcDirs = ['src/main/java/']
        }

        dealsDirectTest {
            res.srcDirs = ['src/dealsDirectRC/res', 'src/commonRes/res']
            java.srcDirs = ['src/main/java/']
        }

        ooRC {
            res.srcDirs = ['src/ooRC/res', 'src/commonRes/res']
            java.srcDirs = ['src/main/java/']
        }

        ooTest {
            res.srcDirs = ['src/ooRC/res', 'src/commonRes/res']
            java.srcDirs = ['src/main/java/']
        }

        buyinviteRC {
            res.srcDirs = ['src/buyinviteRC/res/', 'src/commonRes/res']
            java.srcDirs = ['src/main/java/']
        }

        buyinviteTest {
            res.srcDirs = ['src/buyinviteRC/res/', 'src/commonRes/res']
            java.srcDirs = ['src/main/java/']
        }

        ozsaleRC {
            res.srcDirs = ['src/ozsaleRC/res', 'src/commonRes/res']
            java.srcDirs = ['src/main/java']
        }

        ozsaleTest {
            res.srcDirs = ['src/ozsaleRC/res', 'src/commonRes/res']
            java.srcDirs = ['src/main/java/']
        }

        singsaleRC {
            res.srcDirs = ['src/singsaleRC/res', 'src/commonRes/res']
            java.srcDirs = ['src/main/java/']
        }

        singsaleTest {
            res.srcDirs = ['src/singsaleRC/res', 'src/commonRes/res']
            java.srcDirs = ['src/main/java/']
        }

        nzsaleRC {
            res.srcDirs = ['src/nzsaleRC/res', 'src/commonRes/res']
            java.srcDirs = ['src/main/java/']
        }

        nzsaleTest {
            res.srcDirs = ['src/nzsaleRC/res', 'src/commonRes/res']
            java.srcDirs = ['src/main/java/']
        }

        mysaleRC {
            res.srcDirs = ['src/mysaleRC/res', 'src/commonRes/res']
            java.srcDirs = ['src/main/java/']
        }

        mysaleTest {
            res.srcDirs = ['src/mysaleRC/res', 'src/commonRes/res']
            java.srcDirs = ['src/main/java/']
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    configurations.configureEach {
        resolutionStrategy.force 'com.google.code.findbugs:jsr305:1.3.9'
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }

    dataBinding {
        enabled = true
    }
    buildFeatures {
        buildConfig true
    }
}


repositories {
    flatDir { dirs 'libs' }
    maven {
        url 'https://x.klarnacdn.net/mobile-sdk/'
    }
    maven {
        url "https://cardinalcommerceprod.jfrog.io/artifactory/android"
        credentials {
            username 'braintree_team_sdk'
            password 'AKCp8jQcoDy2hxSWhDAUQKXLDPDx6NYRkqrgFLRc3qDrayg6rrCbJpsKKyMwaykVL8FWusJpp'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'androidx.databinding:databinding-runtime:8.10.1'
    implementation 'androidx.databinding:databinding-adapters:8.10.1'

    // android support libraries
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'androidx.window:window-java:1.4.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.vectordrawable:vectordrawable:1.2.0'
    implementation 'androidx.vectordrawable:vectordrawable-animated:1.2.0'
    implementation 'androidx.activity:activity:1.10.1'

    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'

    // font
    implementation "io.github.inflationx:calligraphy3:3.1.1"
    implementation "io.github.inflationx:viewpump:2.0.3"

    // network
    implementation "com.github.amitshekhariitbhu.Fast-Android-Networking:rx2-android-networking:1.0.4"

    // parser
    implementation "com.google.code.gson:gson:2.11.0"

    // database
    implementation "org.greenrobot:greendao:3.2.2"

    //cookie jar
    implementation "com.github.franmontiel:PersistentCookieJar:v1.0.1"

    // debug database
    debugImplementation "com.github.amitshekhariitbhu.Android-Debug-Database:debug-db:1.0.7"

    // dependency injection
    implementation "com.google.dagger:dagger:2.51.1"
    annotationProcessor "com.google.dagger:dagger-compiler:2.51.1"
    compileOnly 'javax.annotation:jsr250-api:1.0'
    implementation 'javax.inject:javax.inject:1'

    // reactive
    implementation "io.reactivex.rxjava2:rxjava:2.2.21"
    implementation "io.reactivex.rxjava2:rxandroid:2.1.1"

    // code generator for view
    //noinspection AnnotationProcessorOnCompilePath
    implementation "com.jakewharton:butterknife:10.2.3"
    annotationProcessor "com.jakewharton:butterknife-compiler:10.2.3"
    implementation 'com.jakewharton.rxbinding2:rxbinding:2.2.0'

    // logger
    implementation "com.jakewharton.timber:timber:4.5.1"

    // conductor
    implementation "com.bluelinelabs:conductor:3.2.0"
    implementation "com.bluelinelabs:conductor-androidx-transition:3.2.0"
    implementation "com.bluelinelabs:conductor-viewpager:3.2.0"

    // paginate
    implementation "com.github.markomilos:paginate:0.5.1"

    // advanced recyclerview
    implementation('com.h6ah4i.android.widget.advrecyclerview:advrecyclerview:0.11.0@aar')
    // photo view
    implementation "com.github.chrisbanes:PhotoView:2.0.0"
    // circle indicator
    implementation 'me.relex:circleindicator:1.2.2@aar'

    // glide
    implementation "com.github.zjupure:webpdecoder:2.7.4.16.0"
    implementation "com.github.bumptech.glide:glide:4.16.0"
    annotationProcessor "com.github.bumptech.glide:compiler:4.16.0"

    // braintree
    implementation "com.braintreepayments.api:card:4.49.1"
    implementation "com.braintreepayments.api:three-d-secure:4.49.1"
    implementation "com.braintreepayments.api:paypal:4.49.1"
    implementation "com.braintreepayments.api:data-collector:4.49.1"

    // facebook
    implementation "com.facebook.android:facebook-android-sdk:17.0.0"
    implementation "com.facebook.android:facebook-login:17.0.0"

    // GCM
    implementation "com.google.android.gms:play-services-gcm:17.0.0"

    //viewpager indicator
    implementation 'me.relex:circleindicator:1.2.2@aar'

    // sticky headers
    implementation "com.timehop.stickyheadersrecyclerview:library:0.4.3@aar"

    // dependencies for local unit tests
    testImplementation "junit:junit:4.13.2"
    testImplementation "org.mockito:mockito-core:5.12.0"
    testAnnotationProcessor "com.google.dagger:dagger-compiler:2.51.1"
    testImplementation 'org.json:json:20220924'

    // UI Testing
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
    androidTestImplementation 'androidx.test.espresso:espresso-intents:3.6.1'
    androidTestImplementation "org.mockito:mockito-core:5.12.0"
    androidTestAnnotationProcessor "com.google.dagger:dagger-compiler:2.51.1"

    // NR
    implementation 'com.newrelic.agent.android:android-agent:7.5.0'

    // Firebase
    implementation platform('com.google.firebase:firebase-bom:33.15.0')
    implementation 'com.google.firebase:firebase-analytics:22.4.0'
    implementation 'com.google.firebase:firebase-core:21.1.1'
    implementation 'com.google.firebase:firebase-messaging:24.1.1'
    implementation 'com.google.firebase:firebase-crashlytics:19.4.4'

    //VISA CHECKOUT
    implementation 'com.braintreepayments.api:visa-checkout:3.0.0'
    implementation 'com.visa.checkout:visacheckout-android-sdk-6.6.1@aar'

    implementation 'com.squareup.okio:okio:3.4.0'
    implementation 'com.squareup.okhttp3:okhttp:3.12.1'
    implementation group: 'de.greenrobot', name: 'eventbus', version: '2.4.1'

    implementation 'com.google.android.gms:play-services-ads:23.5.0'
    implementation 'androidx.multidex:multidex:2.0.1'

    implementation 'com.stripe:stripe-android:20.23.1'

    implementation 'com.google.android.gms:play-services-wallet:19.4.0'

    // guava
    implementation "com.google.guava:guava:31.1-android"

    // klarna
    implementation 'com.klarna.mobile:sdk:2.6.20'
//    implementation 'com.klarna.checkout:sdk:1.6.15'

    //password strength meter
    implementation 'nu.aaro.gustav:passwordstrengthmeter:0.4'

    //zoom image
    implementation("com.otaliastudios:zoomlayout:1.9.0")

    implementation project(path: ':genie-utility')
    implementation project(path: ':genie-animation')
    implementation project(path: ':genie-views')
    implementation project(path: ':genie-profiler')
    implementation project(path: ':CardForm')
    implementation project(path: ':ptr-lib')
    implementation project(path: ':lib')
    implementation project(path: ':FlowLayout')
    implementation project(path: ':NumberPicker')
    implementation project(path: ':crystal-range-seekbar')
    implementation project(path: ':ahbottomnavigation')


}

// Create New Relic properties file according to flavor
File newRelicProperties = new File("${project.projectDir.absolutePath}/newrelic.properties")
newRelicProperties.createNewFile()


android.applicationVariants.configureEach { variant ->
    variant.productFlavors.each { flavor ->
        def variantSuffix = variant.name.capitalize()
        def generateResourcesTask = project.tasks.named("compile${variantSuffix}Sources").get()
        def generatePropertiesTask = tasks.register("newRelicGenerateProperties${variantSuffix}")
        {
            Properties properties = new Properties()
            properties.load(newRelicProperties.newDataInputStream())
            properties.setProperty("com.newrelic.application_token", flavor.ext.newRelicAppToken)
            properties.store(newRelicProperties.newWriter(), null)
        }.get()
        generateResourcesTask.dependsOn(generatePropertiesTask)
    }

    buildType = variant.name

}

configurations.configureEach {
    resolutionStrategy.force "com.android.support:support-annotations:$supportLibrary"
}

interface InjectedExecOps {
    @Inject
    //@javax.inject.Inject
    ExecOperations getExecOps()
}

//Below tasks is for automation checklist
tasks.register('printVersionName') {
    doLast {
        android.productFlavors.configureEach {
            flavor ->
                if (flavorName.matches(flavor.name)) {
                    println flavor.versionName
                }
        }
    }
}

tasks.register('printVersionCode') {
    doLast {
        android.productFlavors.configureEach {
            flavor ->
                if (flavorName.matches(flavor.name)) {
                    println flavor.versionCode
                }
        }
    }
}

tasks.register('printApplicationId') {
    doLast {
        android.productFlavors.configureEach {
            flavor ->
                if (flavorName.matches(flavor.name)) {
                    println flavor.applicationId
                }
        }
    }
}

tasks.register('printCompileSdkVersion') {
    doLast {
        android.productFlavors.configureEach {
            flavor ->
                if (flavorName.matches(flavor.name)) {
                    println rootProject.ext.compileSdkVersion
                }
        }
    }
}

tasks.register('printMinSdkVersion') {
    doLast {
        android.productFlavors.configureEach {
            flavor ->
                if (flavorName.matches(flavor.name)) {
                    println rootProject.ext.minSdkVersion
                }
        }
    }
}

tasks.register('printTargetSdkVersion') {
    doLast {
        android.productFlavors.configureEach {
            flavor ->
                if (flavorName.matches(flavor.name)) {
                    println rootProject.ext.targetSdkVersion
                }
        }
    }
}

tasks.register('printBuildToolsVersion') {
    doLast {
        android.productFlavors.configureEach {
            flavor ->
                if (flavorName.matches(flavor.name)) {
                    println rootProject.ext.buildToolsVersion
                }
        }
    }
}

tasks.register('printSupportLibrary') {
    doLast {
        android.productFlavors.configureEach {
            flavor ->
                if (flavorName.matches(flavor.name)) {
                    println rootProject.ext.supportLibrary
                }
        }
    }
}

tasks.register('printAppName') {
    doLast {
        android.productFlavors.configureEach {
            flavor ->
                if (flavorName.matches(flavor.name)) {
                    println flavor.ext.appName
                }
        }
    }
}

tasks.register('printFacebookAppId') {
    doLast {
        android.productFlavors.configureEach {
            flavor ->
                if (flavorName.matches(flavor.name)) {
                    println flavor.ext.facebookAppId
                }
        }
    }
}

tasks.register('printFacebookAppSecret') {
    doLast {
        android.productFlavors.configureEach {
            flavor ->
                if (flavorName.matches(flavor.name)) {
                    println flavor.ext.facebookAppSecret
                }
        }
    }
}

tasks.register('printNewRelicAppToken') {
    doLast {
        android.productFlavors.configureEach {
            flavor ->
                if (flavorName.matches(flavor.name)) {
                    println flavor.ext.newRelicAppToken
                }
        }
    }
}


tasks.register('printDebugMode') {

    android.applicationVariants.configureEach {
        variant ->

            doLast {
                android.productFlavors.configureEach {
                    flavor ->
                        if (flavorName.matches(flavor.name) && buildTypeAssemble.matches(variant.name.capitalize())) {
                            if (variant.buildType.name.equalsIgnoreCase("Release")) {
                                println false
                            } else {
                                println true
                            }
                        }
                }
            }


    }
}

tasks.register('parseAdmobAppId') {

    doLast {
        android.productFlavors.configureEach {
            flavor ->
                if (flavorName.matches(flavor.name)) {
                    def xmlFile = "app/src/" + flavorName + "/res/values/strings.xml"
                    def parseXml = new XmlParser().parse(xmlFile)

                    def getAdmobAppId = parseXml.children().get(0)

                    getAdmobAppId.each {
                        println it
                    }
                }
        }
    }

}

tasks.register('parseAdmobBanners') {
    doLast {
        android.productFlavors.configureEach {
            flavor ->
                if (flavorName.matches(flavor.name)) {
                    def xmlFile = "app/src/" + flavorName + "/res/values/strings.xml"
                    def parseXml = new XmlParser().parse(xmlFile)

                    def getAdmobBanners = parseXml.children().get(1)

                    getAdmobBanners.each {
                        println it
                    }
                }
        }
    }
}

tasks.register('parseAdmobProducts') {
    doLast {
        android.productFlavors.configureEach {
            flavor ->
                if (flavorName.matches(flavor.name)) {
                    def xmlFile = "app/src/" + flavorName + "/res/values/strings.xml"
                    def parseXml = new XmlParser().parse(xmlFile)

                    def getAdmobProducts = parseXml.children().get(2)

                    getAdmobProducts.each {
                        println it
                    }
                }
        }
    }
}

tasks.register('parseAdmobAccount') {
    doLast {
        android.productFlavors.configureEach {
            flavor ->
                if (flavorName.matches(flavor.name)) {
                    def xmlFile = "app/src/" + flavorName + "/res/values/strings.xml"
                    def parseXml = new XmlParser().parse(xmlFile)

                    def getAdmobAccount = parseXml.children().get(3)

                    getAdmobAccount.each {
                        println it
                    }
                }
        }
    }
}

tasks.register('getLegacyVersion') {

    android.applicationVariants.configureEach {
        variant ->

            doLast {
                android.productFlavors.configureEach {
                    flavor ->
                        if (flavorName.matches(flavor.name) && buildTypeAssemble.matches(variant.name.capitalize())) {
                            def buildVariant = flavorName + variant.buildType.name.capitalize()
                            def compileWithJavac = "compile" + buildVariant.capitalize() + "JavaWithJavac"
                            def path = project.projectDir.absolutePath + "/build/intermediates/javac/" + buildVariant + "/" + compileWithJavac + "/classes/"
                            def injected = project.objects.newInstance(InjectedExecOps)
                            injected.execOps.javaexec {
                                classpath = files(path)
                                mainClass = "au.com.dealsdirect.data.network.ApiEndPoint"
                            }
                        }

                }

            }

    }
}

tasks.register('printCountryId') {
    android.applicationVariants.configureEach {
        variant ->

            doLast {
                android.productFlavors.configureEach {
                    flavor ->
                        if (flavorName.matches(flavor.name) && buildTypeAssemble.matches(variant.name.capitalize())) {
                            def buildVariant = flavorName + variant.buildType.name.capitalize()
                            def compileWithJavac = "compile" + buildVariant.capitalize() + "JavaWithJavac"
                            def path = project.projectDir.absolutePath + "/build/intermediates/javac/" + buildVariant + "/" + compileWithJavac + "/classes/"
                            def injected = project.objects.newInstance(InjectedExecOps)
                            injected.execOps.javaexec {
                                classpath = files(path)
                                mainClass = "au.com.dealsdirect.ui.controller.main.Settings"
                                args countryName, flavorName, "PRINT_COUNTRY_ID"
                            }
                        }

                }

            }
    }
}

tasks.register('printAccountId') {
    android.applicationVariants.configureEach {
        variant ->

            doLast {
                android.productFlavors.configureEach {
                    flavor ->
                        if (flavorName.matches(flavor.name) && buildTypeAssemble.matches(variant.name.capitalize())) {
                            def buildVariant = flavorName + variant.buildType.name.capitalize()
                            def compileWithJavac = "compile" + buildVariant.capitalize() + "JavaWithJavac"
                            def path = project.projectDir.absolutePath + "/build/intermediates/javac/" + buildVariant + "/" + compileWithJavac + "/classes/"
                            def injected = project.objects.newInstance(InjectedExecOps)
                            injected.execOps.javaexec {
                                classpath = files(path)
                                mainClass = "au.com.dealsdirect.ui.controller.main.Settings"
                                args countryName, flavorName, "PRINT_ACCOUNT_ID"
                            }
                        }

                }

            }
    }
}

tasks.register('printGenieApi') {
    android.applicationVariants.configureEach {
        variant ->

            doLast {
                android.productFlavors.configureEach {
                    flavor ->
                        if (flavorName.matches(flavor.name) && buildTypeAssemble.matches(variant.name.capitalize())) {
                            def buildVariant = flavorName + variant.buildType.name.capitalize()
                            def compileWithJavac = "compile" + buildVariant.capitalize() + "JavaWithJavac"
                            def path = project.projectDir.absolutePath + "/build/intermediates/javac/" + buildVariant + "/" + compileWithJavac + "/classes/"
                            def injected = project.objects.newInstance(InjectedExecOps)
                            injected.execOps.javaexec {
                                classpath = files(path)
                                mainClass = "au.com.dealsdirect.ui.controller.main.Settings"
                                args countryName, flavorName, "PRINT_GENIE_API"
                            }
                        }

                }

            }
    }
}

tasks.register('printCurrencyCode') {
    android.applicationVariants.configureEach {
        variant ->

            doLast {
                android.productFlavors.configureEach {
                    flavor ->
                        if (flavorName.matches(flavor.name) && buildTypeAssemble.matches(variant.name.capitalize())) {
                            def buildVariant = flavorName + variant.buildType.name.capitalize()
                            def compileWithJavac = "compile" + buildVariant.capitalize() + "JavaWithJavac"
                            def path = project.projectDir.absolutePath + "/build/intermediates/javac/" + buildVariant + "/" + compileWithJavac + "/classes/"
                            def injected = project.objects.newInstance(InjectedExecOps)
                            injected.execOps.javaexec {
                                classpath = files(path)
                                mainClass = "au.com.dealsdirect.ui.controller.main.Settings"
                                args countryName, flavorName, "PRINT_CURRENCY_CODE"
                            }
                        }

                }

            }
    }
}

tasks.register('printRecaptcha') {
    doLast {
        android.productFlavors.configureEach {
            flavor ->
                if (flavorName.matches(flavor.name)) {
                    println flavor.ext.reCaptchaSiteKey
                }
        }
    }
}
