apply plugin: 'com.android.application'
apply plugin: 'io.fabric'
apply plugin: 'newrelic'

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion

    lintOptions {
        disable 'MissingTranslation'
    }

    defaultConfig {
        applicationId "au.com.dealsdirect.rc"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        multiDexEnabled true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
    }

    signingConfigs {
        releaseConfig {
            storeFile file('ozsale.keystore')
            storePassword('ozsale')
            keyAlias "ozsale"
            keyPassword "ozsale"
        }
    }

    buildTypes {

        // Always use release variant for deployment to QA and app release
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.releaseConfig
            zipAlignEnabled true

            resValue "bool", "debug_mode", "false"
        }

        // Always use debug variant during development
        debug {
            resValue "bool", "debug_mode", "true"
        }
    }

    flavorDimensions "default"

    productFlavors {
        buyinviteRC {
            versionCode 4
            versionName "0.9"
            applicationId "au.com.buyinvite.bi"

            buildConfigField "String", "API_ROOT", "\"https://www.dealsdirect.com.au/\""
            buildConfigField "String", "API_LEGACY", "\"https://www.dealsdirect.com.au/papi/public/v3.20/\""
            buildConfigField "String", "ACCOUNT_ID", "\"A56B0D62-AEF6-4653-848E-2ECDDB6E9B8C\""

            resValue "string", "app_name", "buyinvite"
            def facebookAppId = "391019637656000"
            resValue "string", "facebook_app_id", facebookAppId
            resValue "string", "facebook_app_secret", "1dea9436118690813bcc315ecfc28705"
            resValue "string", "fb_login_protocol_scheme", "fb" + facebookAppId
            resValue "string", "fb_page_id", "153472458025053"
            resValue "string", "twitter_user_id", "twitter://user?user_id=36309423"
            resValue "string", "default_country_id", "BA"
            resValue "string", "default_language_id", "EN"

            ext.newRelicAppToken = "AAf4ce8e1466bf9d9b7c3dcfdf7c569defebda9edc"
            resValue "string", "new_relic_app_token", ext.newRelicAppToken
        }

        buyinviteTest {
            versionCode 6
            versionName "0.9"
            applicationId "au.com.buyinvite.bi.test"

            buildConfigField "String", "API_ROOT", "\"https://genie-ui-dealsdirect-pre.mysaledev.com/\""
            buildConfigField "String", "API_LEGACY", "\"https://api.mysaledev.com/public/v3.20/\""
            buildConfigField "String", "ACCOUNT_ID", "\"A56B0D62-AEF6-4653-848E-2ECDDB6E9B8C\""

            resValue "string", "app_name", "buyinvite Test"
            def facebookAppId = "171448406947803"
            resValue "string", "facebook_app_id", facebookAppId
            resValue "string", "facebook_app_secret", "df91ab6a34e678773a41839b88d18cdb"
            resValue "string", "fb_login_protocol_scheme", "fb" + facebookAppId
            resValue "string", "fb_page_id", "153472458025053"
            resValue "string", "twitter_user_id", "twitter://user?user_id=36309423"
            resValue "string", "default_country_id", "BA"
            resValue "string", "default_language_id", "EN"

            ext.newRelicAppToken = "AAf4ce8e1466bf9d9b7c3dcfdf7c569defebda9edc"
            resValue "string", "new_relic_app_token", ext.newRelicAppToken
        }

        dealsDirectRC {
            versionCode 71
            versionName "2.3.1"
            applicationId "au.com.dealsdirect"

            buildConfigField "String", "API_ROOT", "\"https://www.dealsdirect.com.au/\""
            buildConfigField "String", "API_LEGACY", "\"https://www.dealsdirect.com.au/papi/public/v3.20/\""
            buildConfigField "String", "ACCOUNT_ID", "\"A56B0D62-AEF6-4653-848E-2ECDDB6E9B8C\""

            resValue "string", "app_name", "DealsDirect"
            def facebookAppId = "1650094968544406"
            resValue "string", "facebook_app_id", facebookAppId
            resValue "string", "facebook_app_secret", "94da0f48bd2ffea25981e52c56f9260a"
            resValue "string", "fb_login_protocol_scheme", "fb" + facebookAppId
            resValue "string", "fb_page_id", "257280167216"
            resValue "string", "twitter_user_id", "twitter://user?user_id=37405859"
            resValue "string", "default_country_id", "DA"
            resValue "string", "default_language_id", "EN"

            ext.newRelicAppToken = "AAa9d543732ff39dddc60c9cb9ad8c9cf22297904b"
            resValue "string", "new_relic_app_token", ext.newRelicAppToken

        }

        dealsDirectTest {
            versionCode 73
            versionName "2.3.1"
            applicationId "au.com.dealsdirect.test"

            buildConfigField "String", "API_ROOT", "\"https://genie-ui-dealsdirect-pre.mysaledev.com/\""
            buildConfigField "String", "API_LEGACY", "\"https://api.mysaledev.com/public/v3.20/\""
            buildConfigField "String", "ACCOUNT_ID", "\"A56B0D62-AEF6-4653-848E-2ECDDB6E9B8C\""

            resValue "string", "app_name", "DealsDirect Test"
            def facebookAppId = "1658400667713836"
            resValue "string", "facebook_app_id", facebookAppId
            resValue "string", "facebook_app_secret", "38e0530d1a0339d117b5474f0731f2af"
            resValue "string", "fb_login_protocol_scheme", "fb" + facebookAppId
            resValue "string", "fb_page_id", "257280167216"
            resValue "string", "twitter_user_id", "twitter://user?user_id=37405859"
            resValue "string", "default_country_id", "DA"
            resValue "string", "default_language_id", "EN"

            ext.newRelicAppToken = "AAa9d543732ff39dddc60c9cb9ad8c9cf22297904b"
            resValue "string", "new_relic_app_token", ext.newRelicAppToken
        }

        ooRC {
            versionCode 11
            versionName "0.9"
            applicationId "au.com.oo"

            buildConfigField "String", "API_ROOT", "\"https://www.oo.com.au/\""
            buildConfigField "String", "API_LEGACY", "\"https://www.oo.com.au/papi/public/v3.20/\""
            buildConfigField "String", "ACCOUNT_ID", "\"25D201EB-9A1C-4045-90B6-E6A9F122C7CB\""

            resValue "string", "app_name", "OO"
            def facebookAppId = "1654976038100746"
            resValue "string", "facebook_app_id", facebookAppId
            resValue "string", "facebook_app_secret", "f372b6a78ffbb38215f796d1a8838bb2"
            resValue "string", "fb_login_protocol_scheme", "fb" + facebookAppId
            resValue "string", "fb_page_id", "10357598833"
            resValue "string", "twitter_user_id", "twitter://user?user_id=14730691"
            resValue "string", "default_country_id", "OA"
            resValue "string", "default_language_id", "EN"

            ext.newRelicAppToken = "AAb0a85221e0d2eb8f185c2c2a34c566840b593941"
            resValue "string", "new_relic_app_token", ext.newRelicAppToken
        }

        ooTest {
            versionCode 15
            versionName "0.9"
            applicationId "au.com.oo.test"

            buildConfigField "String", "API_ROOT", "\"https://genie-ui-oo-pre.mysaledev.com/\""
            buildConfigField "String", "API_LEGACY", "\"https://api.mysaledev.com/public/v3.20/\""
            buildConfigField "String", "ACCOUNT_ID", "\"25D201EB-9A1C-4045-90B6-E6A9F122C7CB\""

            resValue "string", "app_name", "OO Test"
            def facebookAppId = "317133352116634"
            resValue "string", "facebook_app_id", facebookAppId
            resValue "string", "facebook_app_secret", "e0fecfa7b794941aca88ed0840e50d6c"
            resValue "string", "fb_login_protocol_scheme", "fb" + facebookAppId
            resValue "string", "fb_page_id", "10357598833"
            resValue "string", "twitter_user_id", "twitter://user?user_id=14730691"
            resValue "string", "default_country_id", "OA"
            resValue "string", "default_language_id", "EN"

            ext.newRelicAppToken = "AAb0a85221e0d2eb8f185c2c2a34c566840b593941"
            resValue "string", "new_relic_app_token", ext.newRelicAppToken
        }

        topbuyRC {
            versionCode 80
            versionName "2.3.0"
            applicationId "au.com.topbuy"

            buildConfigField "String", "API_ROOT", "\"https://www.topbuy.com.au/\""
            buildConfigField "String", "API_LEGACY", "\"https://www.topbuy.com.au/papi/public/v3.20/\""
            buildConfigField "String", "ACCOUNT_ID", "\"909E0AC5-908A-4A73-8E5C-5312DEEBD24C\""

            resValue "string", "app_name", "TopBuy"
            def facebookAppId = "1544909069170785"
            resValue "string", "facebook_app_id", facebookAppId
            resValue "string", "facebook_app_secret", "fb7a6db2221738ebe78810dff07e1223"
            resValue "string", "fb_login_protocol_scheme", "fb" + facebookAppId
            resValue "string", "fb_page_id", "47143367223"
            resValue "string", "twitter_user_id", "twitter://user?user_id=20105193"
            resValue "string", "default_country_id", "TA"
            resValue "string", "default_language_id", "EN"

            ext.newRelicAppToken = "AA17bba4366f389b0ca3e7c8068935df33ce10bd35"
            resValue "string", "new_relic_app_token", ext.newRelicAppToken
        }

        topbuyTest {
            versionCode 82
            versionName "2.3.0"
            applicationId "au.com.topbuy.test"

            buildConfigField "String", "API_ROOT", "\"https://geniemobileappsclientapi.herokuapp.com/sandbox/\""
            buildConfigField "String", "API_LEGACY", "\"https://geniemobileappsclientapi.herokuapp.com/sandbox/public/v3.20/\""
            buildConfigField "String", "ACCOUNT_ID", "\"909E0AC5-908A-4A73-8E5C-5312DEEBD24C\""

            resValue "string", "app_name", "TopBuy Test"
            def facebookAppId = "1544909372504088"
            resValue "string", "facebook_app_id", facebookAppId
            resValue "string", "facebook_app_secret", "c1c38e066ad13cc4987929e3c2f73770"
            resValue "string", "fb_login_protocol_scheme", "fb" + facebookAppId
            resValue "string", "fb_page_id", "47143367223"
            resValue "string", "twitter_user_id", "twitter://user?user_id=20105193"
            resValue "string", "default_country_id", "TA"
            resValue "string", "default_language_id", "EN"

            ext.newRelicAppToken = "AA17bba4366f389b0ca3e7c8068935df33ce10bd35"
            resValue "string", "new_relic_app_token", ext.newRelicAppToken
        }

        ourpayTest {
            versionCode 4
            versionName "0.9"
            applicationId "au.com.ourpay.test"

            buildConfigField "String", "API_ROOT", "\"https://www.dealsdirect.com.au/\""
            buildConfigField "String", "API_LEGACY", "\"https://www.dealsdirect.com.au/papi/public/v3.20/\""
            buildConfigField "String", "ACCOUNT_ID", "\"A56B0D62-AEF6-4653-848E-2ECDDB6E9B8C\""

            resValue "string", "app_name", "Ourpay Test"
            def facebookAppId = "1650094968544406"
            resValue "string", "facebook_app_id", facebookAppId
            resValue "string", "facebook_app_secret", "94da0f48bd2ffea25981e52c56f9260a"
            resValue "string", "fb_login_protocol_scheme", "fb" + facebookAppId
            resValue "string", "fb_page_id", "257280167216"
            resValue "string", "new_relic_app_token", "AAa9d543732ff39dddc60c9cb9ad8c9cf22297904b"
            resValue "string", "twitter_user_id", "twitter://user?user_id=37405859"
            resValue "string", "default_country_id", "DA"
            resValue "string", "default_language_id", "EN"

            ext.newRelicAppToken = "asjdasldkalsnasdT"
            resValue "string", "new_relic_app_token", ext.newRelicAppToken
        }

        ozsaleRC {
            versionCode 10
            versionName "0.9"
            applicationId "au.com.ozsale"

            buildConfigField "String", "API_ROOT", "\"https://www.ozsale.com.au/\""
            buildConfigField "String", "API_LEGACY", "\"https://www.ozsale.com.au/papi/public/v3.22/\""
            buildConfigField "String", "ACCOUNT_ID", "\"A56B0D62-AEF6-4653-848E-2ECDDB6E9B8C\""

            resValue "string", "app_name", "Ozsale"
            def facebookAppId = "1650094968544406"
            resValue "string", "facebook_app_id", facebookAppId
            resValue "string", "facebook_app_secret", "94da0f48bd2ffea25981e52c56f9260a"
            resValue "string", "fb_login_protocol_scheme", "fb" + facebookAppId
            resValue "string", "fb_page_id", "257280167216"
            resValue "string", "twitter_user_id", "twitter://user?user_id=37405859"
            resValue "string", "default_country_id", "DA"
            resValue "string", "default_language_id", "EN"

            ext.newRelicAppToken = "AAa9d543732ff39dddc60c9cb9ad8c9cf22297904b"
            resValue "string", "new_relic_app_token", ext.newRelicAppToken

        }


        ozsaleTest {
            versionCode 2
            versionName "0.9"
            applicationId "au.com.ozsaleTest"

            buildConfigField "String", "API_ROOT", "\"https://genie-ui-dealsdirect-pre.mysaledev.com/\""
            buildConfigField "String", "API_LEGACY", "\"https://api.mysaledev.com/public/v3.24/\""
            buildConfigField "String", "ACCOUNT_ID", "\"A56B0D62-AEF6-4653-848E-2ECDDB6E9B8C\""

            resValue "string", "app_name", "Ozsale Test"
            def facebookAppId = "1650094968544406"
            resValue "string", "facebook_app_id", facebookAppId
            resValue "string", "facebook_app_secret", "94da0f48bd2ffea25981e52c56f9260a"
            resValue "string", "fb_login_protocol_scheme", "fb" + facebookAppId
            resValue "string", "fb_page_id", "257280167216"
            resValue "string", "twitter_user_id", "twitter://user?user_id=37405859"
            resValue "string", "default_country_id", "DA"
            resValue "string", "default_language_id", "EN"

            ext.newRelicAppToken = "AAa9d543732ff39dddc60c9cb9ad8c9cf22297904b"
            resValue "string", "new_relic_app_token", ext.newRelicAppToken

        }
    }

    sourceSets {
        dealsDirectRC {
            java.srcDirs = ['src/commonControllers/java/',
                            'src/commonHomeController/java/',
                            'src/commonCategoriesController/java/',
                            'src/commonSaleItemsController/java/',
                            'src/commonSearchFilterController/java/',
                            'src/commonReturnsControllers/java/',
                            'src/commonShopsController/java/',
                            'src/commonOrdersController/java',
                            'src/commonMainController/java/',
                            'src/commonActivity/java/',
                            'src/dealsDirectRC/java/',
                            'src/main/java/']
        }

        dealsDirectTest {
            java.srcDirs = ['src/commonControllers/java/',
                            'src/commonHomeController/java/',
                            'src/commonCategoriesController/java/',
                            'src/commonSaleItemsController/java/',
                            'src/commonSearchFilterController/java/',
                            'src/commonReturnsControllers/java/',
                            'src/commonOrdersController/java',
                            'src/commonShopsController/java/',
                            'src/commonMainController/java/',
                            'src/commonActivity/java/',
                            'src/dealsDirectRC/java/',
                            'src/main/java/']
        }

        ooRC {
            res.srcDir 'src/ooTest/res/'
            java.srcDirs = ['src/commonControllers/java/',
                            'src/commonHomeController/java/',
                            'src/commonCategoriesController/java/',
                            'src/commonSaleItemsController/java/',
                            'src/commonSearchFilterController/java/',
                            'src/commonReturnsControllers/java/',
                            'src/commonOrdersController/java',
                            'src/commonShopsController/java/',
                            'src/commonMainController/java/',
                            'src/commonActivity/java/',
                            'src/ooTest/java/',
                            'src/main/java/']
        }

        ooTest {
            res.srcDir 'src/ooTest/res/'
            java.srcDirs = ['src/commonControllers/java/',
                            'src/commonHomeController/java/',
                            'src/commonCategoriesController/java/',
                            'src/commonSaleItemsController/java/',
                            'src/commonSearchFilterController/java/',
                            'src/commonReturnsControllers/java/',
                            'src/commonOrdersController/java',
                            'src/commonShopsController/java/',
                            'src/commonMainController/java/',
                            'src/commonActivity/java/',
                            'src/ooTest/java/',
                            'src/main/java/']
        }

        buyinviteRC {
            res.srcDir 'src/buyinviteTest/res/'
            java.srcDirs = ['src/commonControllers/java/',
                            'src/commonHomeController/java/',
                            'src/commonCategoriesController/java/',
                            'src/commonSaleItemsController/java/',
                            'src/commonSearchFilterController/java/',
                            'src/commonReturnsControllers/java/',
                            'src/commonOrdersController/java',
                            'src/commonShopsController/java/',
                            'src/commonMainController/java/',
                            'src/commonActivity/java/',
                            'src/buyinviteTest/java/',
                            'src/main/java/']
        }

        buyinviteTest {
            java.srcDirs = ['src/commonControllers/java/',
                            'src/commonHomeController/java/',
                            'src/commonCategoriesController/java/',
                            'src/commonSaleItemsController/java/',
                            'src/commonSearchFilterController/java/',
                            'src/commonReturnsControllers/java/',
                            'src/commonOrdersController/java',
                            'src/commonShopsController/java/',
                            'src/commonMainController/java/',
                            'src/commonActivity/java/',
                            'src/buyinviteTest/java/',
                            'src/main/java']
        }

        ourpayTest {
            java.srcDirs = ['src/ourpayTest/java/',
                            'src/commonControllers/java/',
                            'src/commonOrdersController/java',
                            'src/main/java/']
        }

        topbuyTest {
            res.srcDir 'src/topbuyRC/res/'
            java.srcDirs = ['src/topbuyRC/java/', 'src/main/java/']
        }

        topbuyRC {
            res.srcDir 'src/topbuyRC/res/'
            java.srcDirs = ['src/topbuyRC/java/', 'src/main/java/']
        }

        ozsaleRC {
            res.srcDir 'src/ozsaleRC/res/'
            java.srcDirs = ['src/ozsaleRC/java',
                            'src/commonControllers/java/',
                            'src/commonShopsController/java/',
                            'src/main/java/']
        }

        ozsaleTest {
            res.srcDir 'src/ozsaleRC/res/'
            java.srcDirs = ['src/ozsaleRC/java',
                            'src/commonControllers/java/',
                            'src/commonShopsController/java/',
                            'src/main/java/']
        }

        main {
            java.srcDirs = ['src/main/java']
            resources.srcDirs = ['src/main/resources']
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    configurations.all {
        resolutionStrategy.force 'com.google.code.findbugs:jsr305:1.3.9'
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }
}




dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])

    // android support libraries
    compile "com.android.support:appcompat-v7:$rootProject.supportLibrary"
    compile "com.android.support:recyclerview-v7:$rootProject.supportLibrary"
    compile "com.android.support:cardview-v7:$rootProject.supportLibrary"
    compile "com.android.support:design:$rootProject.supportLibrary"
    compile "com.android.support:support-vector-drawable:$rootProject.supportLibrary"
    compile "com.android.support:animated-vector-drawable:$rootProject.supportLibrary"

    // font
    compile "uk.co.chrisjenx:calligraphy:$rootProject.calligraphyVersion"

    // network
    compile "com.amitshekhar.android:rx2-android-networking:$rootProject.rx2FastAndroidNetworking"

    // parser
    compile "com.google.code.gson:gson:$rootProject.gsonVersion"

    // database
    compile "org.greenrobot:greendao:$rootProject.greenDaoVersion"

    //cookie jar
    compile "com.github.franmontiel:PersistentCookieJar:$rootProject.cookieJarVersion"

    // debug database
    debugCompile "com.amitshekhar.android:debug-db:$rootProject.debugDBVersion"

    // dependency injection
    compile "com.google.dagger:dagger:$rootProject.dagger2Version"
    annotationProcessor "com.google.dagger:dagger-compiler:$rootProject.dagger2Version"
    provided 'javax.annotation:jsr250-api:1.0'
    compile 'javax.inject:javax.inject:1'

    // reactive
    compile "io.reactivex.rxjava2:rxjava:$rootProject.rxjava2Version"
    compile "io.reactivex.rxjava2:rxandroid:$rootProject.rxandroidVersion"

    // code generator for view
    compile "com.jakewharton:butterknife:$rootProject.butterKnifeVersion"
    annotationProcessor "com.jakewharton:butterknife-compiler:$rootProject.butterKnifeVersion"

    // swipe view
    compile "com.mindorks:placeholderview:$rootProject.placeholderviewVersion"

    // logger
    compile "com.jakewharton.timber:timber:$rootProject.timberVersion"

    // conductor
    compile "com.bluelinelabs:conductor:$rootProject.conductorVersion"
    compile "com.bluelinelabs:conductor-support:$rootProject.conductorVersion"

    // paginate
    compile "com.github.markomilos:paginate:$rootProject.paginateVersion"

    // leak canary
    debugCompile "com.squareup.leakcanary:leakcanary-android:$rootProject.leakCanaryVersion"
    releaseCompile "com.squareup.leakcanary:leakcanary-android-no-op:$rootProject.leakCanaryVersion"

    // recycler view pager
    compile "com.github.lsjwzh.RecyclerViewPager:lib:$rootProject.recyclerViewPagerVersion"
    // flow layout
    compile "com.zhy:flowlayout-lib:$rootProject.flowLayoutVersion"
    // photo view
    compile "com.github.chrisbanes:PhotoView:$rootProject.photoViewVersion"
    // bottom navigation
    compile 'com.aurelhubert:ahbottomnavigation:2.0.6'
    // circle indicator
    compile 'me.relex:circleindicator:1.2.2@aar'

    // glide
    compile "com.github.bumptech.glide:glide:$rootProject.glideVersion"

    // guava
    compile "com.google.guava:guava:$rootProject.guavaVersion"

    // braintree
    compile "com.braintreepayments.api:braintree:$rootProject.braintreeVersion"
    compile "com.braintreepayments.api:data-collector:$rootProject.braintreeVersion"

    // facebook
    compile "com.facebook.android:facebook-android-sdk:$rootProject.facebookVersion"
    implementation "com.facebook.android:facebook-login:$rootProject.facebookVersion"

    // GCM
    compile "com.google.android.gms:play-services-gcm:$rootProject.gcmVersion"

    // Crystal Range Seekbar
    compile "com.crystal:crystalrangeseekbar:$rootProject.crystalRangeSeekbarVersion"

    //viewpager indicator
    compile 'me.relex:circleindicator:1.2.2@aar'

    // dependencies for local unit tests
    testCompile "junit:junit:$rootProject.ext.junitVersion"
    testCompile "org.mockito:mockito-core:$rootProject.mockitoVersion"
    testAnnotationProcessor "com.google.dagger:dagger-compiler:$rootProject.dagger2Version"
    testCompile 'org.json:json:20160810'

    // UI Testing
    androidTestCompile "com.android.support.test.espresso:espresso-core:$rootProject.espressoVersion"
    androidTestCompile "com.android.support.test.espresso:espresso-intents:$rootProject.espressoVersion"
    androidTestCompile "org.mockito:mockito-core:$rootProject.mockitoVersion"
    androidTestAnnotationProcessor "com.google.dagger:dagger-compiler:$rootProject.dagger2Version"

    // CLS
    compile('com.crashlytics.sdk.android:crashlytics:2.6.8@aar') {
        transitive = true
    }

    // Answers
    compile('com.crashlytics.sdk.android:answers:1.3.13@aar') {
        transitive = true
    }

    // NR
    compile 'com.newrelic.agent.android:android-agent:5.14.0'

    compile project(path: ':genie-utility')
    compile project(path: ':genie-animation')
    compile project(path: ':genie-views')
    compile project(path: ':CardForm')
    compile project(path: ':ptr-lib')

}

// Create New Relic properties file according to flavor
File newRelicProperties = new File("${project.projectDir.absolutePath}/newrelic.properties")
newRelicProperties.createNewFile()

android.applicationVariants.all { variant ->
    variant.productFlavors.each { flavor ->
        def variantSuffix = variant.name.capitalize()
        def generateResourcesTask = project.tasks.getByName("compile${variantSuffix}Sources")
        def generatePropertiesTask = task("newRelicGenerateProperties${variantSuffix}") << {
            Properties properties = new Properties()
            properties.load(newRelicProperties.newDataInputStream())
            properties.setProperty("com.newrelic.application_token", flavor.ext.newRelicAppToken)
            properties.store(newRelicProperties.newWriter(), null)
        }
        generateResourcesTask.dependsOn generatePropertiesTask
    }
}

configurations.all {
    resolutionStrategy.force "com.android.support:support-annotations:$supportLibrary"
}

apply plugin: 'com.google.gms.google-services'
