# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.61.0"

# Fabric Token and Secret
API_TOKEN = '156e897ec909d04276fe681aef03572370ac089e'
BUILD_SECRET = 'e048a220b52f841eef5e6862bc43a56a5a51841da934f1e0b76a5019c630c661'

# You can list more emails here
  live_emails = '"
  ericapena@apacsale.com,
  jelinepena@gmail.com,
  elainedizon@mysale.com,
  ruz@apacsale.com,
  michael@smartwave.ph,
  jc@mysale.com,
  elaine@smartwave.ph,
  chindee@smartwave.ph,
  ejptacc123@gmail.com,
"'

# You can list more emails here
  test_emails = '"
  ayi@smartwave.ph,
  ericapena@apacsale.com,
  jelinepena@gmail.com,
  elainedizon@mysale.com,
  ruz@apacsale.com,
  jc@mysale.com,
  elaine@smartwave.ph,
  chindee@smartwave.ph
"'

# You can list more emails here
  dev_emails = '"
  PaulDeSilva@mysale.com,
  elainedizon@mysale.com,
  diofelpallega@mysale.com,
  ayicatimpo@mysale.com,
  JulianPaul@mysale.com,
  ChindeeTubasis@mysale.com,
  michael@smartwave.ph,
  EricaPena@mysale.com,
  jc@apacsale.com
"'

default_platform :android

# Uploads the app to Fabric
def uploadToFabric(app_name, emails, apk_name, app_path, app_flavor)
projectDir = app_path + '/app/build/outputs/apk/' + app_flavor + '/release/'
  puts "Uploading to fabric"
    tries = 3
    begin
      # Optional, lets you filter out merge commits
      #changelog_from_git_commits(merge_commit_filtering: 'exclude_merges')

      crashlytics(api_token: API_TOKEN,
           build_secret: BUILD_SECRET,
                 emails: emails,
               apk_path: projectDir + apk_name,
          notifications: true)
    rescue Exception => e
      puts e
      if tries > 0
        retry
      else
        puts "Error uploading"
      end
    end
end

# Builds the app with scheme name
def build(build_variant, app_flavor)
  increment_version_code_android(product_flavor: app_flavor)
  gradle(task: "assemble", flavor: build_variant)
end

# Displays emails on which the build will be sent to
def displayEmails(emails)
  puts "----------------------"
  puts "--Sending emails to:--"
  puts "----------------------"
  puts emails
  puts "----------------------"
end

lane :dd_build do |options|
  build(options[:build_variant], options[:app_flavor])

  emails = options[:emails]

  displayEmails(emails)

  uploadToFabric(options[:app_name], emails, options[:apk_name], options[:app_path], options[:app_flavor])
end

lane :fabric_deploy_ba_test do
  Dir.chdir("..")
  app_dir = Dir.pwd

  #Change apk_name and app_name for other flavors
  sh "fastlane dd_build app_name:'BuyinviteTest' emails:" + dev_emails + " apk_name:" + 'app-buyinviteTest-debug.apk' + " build_variant:" + 'buyinviteTestDebug' + " app_path:" + app_dir + " app_flavor:" + 'buyinviteTest'
 end

lane :fabric_deploy_ba_rc do
  Dir.chdir("..")
  app_dir = Dir.pwd

  #Change apk_name and app_name for other flavors
  sh "fastlane dd_build app_name:'Buyinvite' emails:" + dev_emails + " apk_name:" + 'app-buyinviteRC-debug.apk' + " build_variant:" + 'buyinviteRCDebug' + " app_path:" + app_dir+ " app_flavor:" + 'buyinviteRC'
 end

lane :fabric_deploy_dd_test do
  Dir.chdir("..")
  app_dir = Dir.pwd

  #Change apk_name and app_name for other flavors
  sh "fastlane dd_build app_name:'DealsDirectTest' emails:" + dev_emails + " apk_name:" + 'app-dealsDirectTest-release.apk' + " build_variant:" + 'DealsDirectTestRelease' + " app_path:" + app_dir + " app_flavor:" + 'dealsDirectTest'
 end

lane :fabric_deploy_dd_rc do
  Dir.chdir("..")
  app_dir = Dir.pwd

  #Change apk_name and app_name for other flavors
  sh "fastlane dd_build app_name:'DealsDirect' emails:" + dev_emails + " apk_name:" + 'app-dealsDirectRC-release.apk' + " build_variant:" + 'DealsDirectRCRelease' + " app_path:" + app_dir+ " app_flavor:" + 'dealsDirectRC'
 end

 lane :fabric_deploy_oo_rc do
   Dir.chdir("..")
   app_dir = Dir.pwd

   #Change apk_name and app_name for other flavors
   sh "fastlane dd_build app_name:'ooRC' emails:" + dev_emails + " apk_name:" + 'app-ooRC-release.apk' + " build_variant:" + 'ooRCRelease' + " app_path:" + app_dir + " app_flavor:" + 'ooRC'
  end

lane :fabric_deploy_oo_test do
  Dir.chdir("..")
  app_dir = Dir.pwd

  #Change apk_name and app_name for other flavors
  sh "fastlane dd_build app_name:'ooTest' emails:" + dev_emails + " apk_name:" + 'app-ooTest-release.apk' + " build_variant:" + 'ooTestRelease' + " app_path:" + app_dir + " app_flavor:" + 'ooTest'
 end

lane :fabric_deploy_lc_test do
  Dir.chdir("..")
  app_dir = Dir.pwd

  #Change apk_name and app_name for other flavors
  sh "fastlane dd_build app_name:'londonChicTest' emails:" + dev_emails + " apk_name:" + 'app-londonChicTest-release.apk' + " build_variant:" + 'londonChicTestRelease' + " app_path:" + app_dir + " app_flavor:" + 'londonChicTest'
end

lane :fabric_deploy_tb_test do
  Dir.chdir("..")
  app_dir = Dir.pwd

  #Change apk_name and app_name for other flavors
  sh "fastlane dd_build app_name:'topbuy Test' emails:" + dev_emails + " apk_name:" + 'app-topbuyTest-release.apk' + " build_variant:" + 'topbuyTestRelease' + " app_path:" + app_dir + " app_flavor:" + 'topbuyTest'
end
